version: '3'
networks:
  Lara:
    driver: bridge
services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
      - ./config/php/php.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "9000:9000"
    container_name: php
    networks:
      - Lara
  database:
    image: mariadb:latest
    container_name: lara-mariadb
    ports:
      - "3306:3306"
    restart: unless-stopped
    tty: true
    networks:
      - Lara
    env_file:
      - ./docker-compose.env
    volumes:
      - ./:/var/www
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lara-phpmyadmin
    environment:
      PMA_HOST: lara-mariadb
      PMA_PORT: 3306
    ports:
      - '8080:80'
    networks:
      - Lara
  web:
    image: nginx:latest
    container_name: lara-nginx
    ports:
      - "0.0.0.0:80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - database
      - php
    networks:
      - Lara
